name: My First CI Pipeline
on:
  push:
    branches:
      - main

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Say hello
        run: echo "Hello from GitHub actions! This pipeline ran automatically."

      - name: Show current date
        run: date

      - name: List repo files
        run: ls -la
